name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test-run:
    runs-on: [self-hosted, linux, x64]  # Passe an, falls du eigene Labels vergeben hast
    steps:
      - name: Check runner
        run: echo "Hello from self-hosted runner!"
