name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: self-hosted
    steps:
      - name: Test step
        run: echo "Hello from self-hosted runner!"

